server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation   # 聚合
    # active: dev         # 微服务
  data:
    redis:
      host: 192.168.8.128
      port: 6379
      password: 123456
      database: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848