server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.8.128
      port: 6379
      password: 123456
      database: 1
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: be1d98a6c0df089755b6457d0253ffae
  goto-domain:
    white-list:
      enable: false   # 开启
      names: '拿个offer,知乎,掘金,博客园,抖音,B站,力扣'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - douyin.com
        - bilibili.com
        - leetcode.cn

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
